module.exports.SITE_URL = 'https://kmkzt.dev'
module.exports.SITE_NAME = 'kmkzt.dev'
module.exports.SITE_DESCRIPTION = '個人学習の内容を書くブログ。'
module.exports.GITHUB_ACCOUNT = 'kmkzt'
module.exports.TWITTER_ACCOUNT = 'kameikazuto'
module.exports.GA_TRACKING_ID = 'UA-91428067-3'
