#!/usr/bin/env bash

# BACKUP MEMO: update timestamp
# git status　\
# | git diff --name-only --staged --diff-filter=M
# | grep -E \"_posts/.*.md$\"
# | xargs -L 1 scripts/update-time.js

# Project config
POSTS_DIR="_posts"

# Git status on stage
FILTER_UPDATE_POST="git diff --name-only --staged --diff-filter=M | grep -E \"${POSTS_DIR}/.*.md$\""

echo -n -e "\n"
echo "Get markdown list command:"
echo $FILTER_UPDATE_POST
echo -n -e "\n"
echo "Markdown list:"
eval $FILTER_UPDATE_POST
echo -n -e "\n"

# Update markdown of posts
eval $FILTER_UPDATE_POST | xargs -L 1 echo 'UPDATE POST: \n'
eval $FILTER_UPDATE_POST | xargs -L 1 scripts/update-time.js
eval $FILTER_UPDATE_POST | xargs -L 1 git add
